set -g default-command ${SHELL}
set -g default-shell ${SHELL}

set -g default-terminal "screen-256color"
set -as terminal-features ",*:RGB"
set -as terminal-features ',*:Smulx=\E[4::%p1%dm'
set -as terminal-features ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'



unbind C-b


set -g prefix C-a
bind C-a send-prefix
set -g base-index 1
set -g renumber-windows on
set-option -g allow-rename off
set -g mouse on
set -g @continuum-restore 'on'
set -g @resurrect-processes 'false'
set -g status-keys vi
set -g status-interval 1
set -g status-justify centre

bind -n C-k clear-history

## mouse wheel scroll settings 
bind-key -T copy-mode-vi WheelUpPane select-pane \; send-keys -X -N 1 scroll-up
bind-key -T copy-mode-vi WheelDownPane select-pane \; send-keys -X -N 1 scroll-down

# shortcuts for windows. 
bind-key F switch-client -t GCG:FlexGet.1
bind-key D switch-client -t GCG:dotfiles.0

set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

set-hook -g client-dark-theme 'set -g @ukiyo-theme "kanagawa/dragon" ; source-file ~/.config/tmux/tmux.conf'
set-hook -g client-light-theme 'set -g @ukiyo-theme "kanagawa/lotus" ; source-file ~/.config/tmux/tmux.conf'
# set -g @ukiyo-plugins "battery cpu-usage time weather"
set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.config/tmux/plugins/tpm-redux/tpm'
