# Path to your oh-my-zsh installation.
export ZSH=/home/gcg/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="spaceship"
#ZSH_THEME="agnoster"
#ZSH_THEME="amuse"

# powerlevel9k custom methods
custom_php_version(){
    local count_php_files
    count_php_files=`ls -1 *.php 2>/dev/null | wc -l`
    local php_version
    php_version=$(php -r 'echo PHP_MAJOR_VERSION . "." . PHP_MINOR_VERSION . "." . PHP_RELEASE_VERSION;')
    if [[ -n "$php_version" ]] && [[ $count_php_files != 0 ]]; then
        echo -n " $php_version"
    fi
}
custom_node_version(){
    local node_version=$(node -v 2>/dev/null)
    [[ -z "${node_version}" ]] && return
    if [[ -f "package.json" ]]; then
        echo -n " ${node_version:1}"
    fi
}
custom_go_version(){
    local go_version
    local go_path
    local count_go_files
    go_version=$(go version 2>/dev/null | sed -E "s/.*(go[0-9.]*).*/\1/")
    go_path=$(go env GOPATH 2>/dev/null)
    count_go_files=`ls -1 *.go 2>/dev/null | wc -l`
    if [[ -n "$go_version" && "${PWD##$go_path}" != "$PWD" ]] && [[ $count_go_files != 0 ]]; then
        echo -n " $go_version"
    fi
}
custom_laravel_version(){
    local laravel_version="$(php artisan --version 2> /dev/null)"
    if [[ -n "${laravel_version}" && "${laravel_version}" =~ "Laravel Framework" ]]; then
        # Strip out everything but the version
        laravel_version="${laravel_version//Laravel Framework /}"
        echo -n " ${laravel_version}"
    fi
}

# Current active font: SauceCode Pro from Nerd Fonts
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=20
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_absolute"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status custom_php custom_laravel custom_node custom_go)
POWERLEVEL9K_DISABLE_PROMPT=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' '
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_CUSTOM_PHP="custom_php_version"
POWERLEVEL9K_CUSTOM_LARAVEL="custom_laravel_version"
POWERLEVEL9K_CUSTOM_NODE="custom_node_version"
POWERLEVEL9K_CUSTOM_GO="custom_go_version"
POWERLEVEL9K_CUSTOM_PHP_BACKGROUND='104'
POWERLEVEL9K_CUSTOM_PHP_FOREGROUND='white'
POWERLEVEL9K_CUSTOM_NODE_BACKGROUND='118'
POWERLEVEL9K_CUSTOM_NODE_FOREGROUND='black'
POWERLEVEL9K_CUSTOM_GO_FOREGROUND='white'
POWERLEVEL9K_CUSTOM_GO_BACKGROUND='014'
POWERLEVEL9K_CUSTOM_LARAVEL_BACKGROUND='maroon'
POWERLEVEL9K_CUSTOM_LARAVEL_FOREGROUND='white'
POWERLEVEL9K_VCS__BACKGROUND='white'
POWERLEVEL9K_VCS_SHORTEN_LENGTH=30
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=30
POWERLEVEL9K_VCS_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_VCS_SHORTEN_DELIMITER=".."
ZSH_THEME="powerlevel9k/powerlevel9k"



plugins=(git github go golang redis-cli bower bundler cake capistrano composer npm zsh_reload laravel4 laravel5 git-flow docker)

# User configuration

source $ZSH/oh-my-zsh.sh

DISABLE_AUTO_TITLE=true

alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias zshrc="vim ~/.zshrc && reload"
alias i3rc="vim ~/.config/i3/config"
alias vimrc="vim ~/.vimrc"
alias tmuxrc="vim ~/.tmux.conf && tmux source-file ~/.tmux.conf"
alias aptup="sudo apt update && sudo apt upgrade && sudo apt autoremove"
alias up="sudo apt update|lolcat && sudo apt upgrade|lolcat && sudo apt autoremove|lolcat && composer global update && npm update -g && gem update --system|lolcat && sudo snap refresh|lolcat"
alias top="gotop -psbc monokai"
alias iftop="sudo iftop"
alias powertop="sudo powertop"
alias fuck='sudo "$BASH" -c "$(history p !!)"'
alias work="cd ~/Work/src/github.com/"
alias gml="git checkout master && git pull && git remote prune origin"
alias privatefox="firefox -private"
alias inchrome="google-chrome --incognito"
alias macos="cd ~/Downloads/macOS && sh basic.sh"
alias listwifis='nmcli -f in-use,ssid,bssid,signal,bars dev wifi'
alias latestdocker='docker exec -it `docker ps -q --latest` /bin/sh'

export GOPATH=$HOME/Work
export GO111MODULE=on
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export ANDROID_HOME=$HOME/Android/Sdk
export REACT_EDITOR=vim
export EDITOR=vim
export EVENT_NOKQUEUE=1
export GPG_TTY=$(tty)
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export NVM_DIR="/home/gcg/.nvm"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/games"
export PATH=$PATH:/snap/bin
export PATH=$PATH:$GOPATH/bin

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH="/usr/local/sbin:$PATH"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$HOME/Apps/Postman:$PATH"
export PATH="$HOME/Apps/android-studio:$PATH"
export PATH="$PATH:$HOME/.npm/bin"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$PATH:$HOME/.config/composer/vendor/bin"
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$HOME/.tmux/bin
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

eval "$(rbenv init -)"
