# Path to your oh-my-zsh installation.
export ZSH=/home/gcg/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="spaceship"
ZSH_THEME="spaceship"

plugins=(git github go golang redis-cli battery bower bundler cake capistrano composer npm zsh_reload laravel4 laravel5 git-flow docker)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
source $ZSH/oh-my-zsh.sh
export PATH=$PATH:/snap/bin


alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias zshrc="vim ~/.zshrc && reload"
alias i3rc="vim ~/.config/i3/config"
alias vimrc="vim ~/.vimrc"
alias tmuxrc="vim ~/.tmux.conf && tmux source-file ~/.tmux.conf"
alias aptup="sudo apt update |lolcat && sudo apt upgrade |lolcat && sudo apt autoremove|lolcat"
alias up="sudo apt update |lolcat && sudo apt upgrade |lolcat && sudo apt autoremove|lolcat && composer global update && npm update -g && sudo gem update --system && sudo snap refresh | lolcat"
alias top="gotop -psbc monokai"
alias iftop="sudo iftop"
alias powertop="sudo powertop"
alias fuck='sudo "$BASH" -c "$(history p !!)"'
alias work="cd ~/Work/src/github.com/"
alias gml="git checkout master && git pull && git remote prune origin"
alias privatefox="firefox -private"
alias inchrome="google-chrome --incognito"

alias listwifis='nmcli -f in-use,ssid,bssid,signal,bars dev wifi'
# Gopath settings
export GOPATH=$HOME/Work
export PATH=$PATH:$GOPATH/bin
export GO111MODULE=on


### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

# tmux scripts to the bin
export PATH=$PATH:$HOME/.tmux/bin


DISABLE_AUTO_TITLE=true

export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export REACT_EDITOR=vim
export EDITOR=vim
export PATH=~/.composer/vendor/bin:$PATH
export PATH=~/Library/Python/2.7/bin:$PATH
export NVM_DIR="/home/gcg/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH="/usr/local/sbin:$PATH"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# for aws and eb cli
export PATH="$HOME/.local/bin:$PATH"
# for yarn
export PATH="$HOME/.yarn/bin:$PATH"

export EVENT_NOKQUEUE=1

export PATH="$HOME/Apps/Postman:$PATH"
export PATH="$HOME/Apps/android-studio:$PATH"

export GPG_TTY=$(tty)


export PATH=$PATH:/home/gcg/.local/bin

export PATH="$PATH:$HOME/.npm/bin"



export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1


source "/home/gcg/.oh-my-zsh/custom/themes/spaceship.zsh-theme"


source "/home/gcg/.oh-my-zsh/custom/themes/spaceship.zsh-theme"


source "/home/gcg/.oh-my-zsh/custom/themes/spaceship.zsh-theme"


source "/home/gcg/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
