# Path to your oh-my-zsh installation.
export ZSH=/home/gcg/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="spaceship"
#ZSH_THEME="agnoster"
ZSH_THEME="amuse"

plugins=(git github go golang redis-cli bower bundler cake capistrano composer npm zsh_reload laravel4 laravel5 git-flow docker)

# User configuration

source $ZSH/oh-my-zsh.sh

DISABLE_AUTO_TITLE=true

alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias zshrc="vim ~/.zshrc && reload"
alias i3rc="vim ~/.config/i3/config"
alias vimrc="vim ~/.vimrc"
alias tmuxrc="vim ~/.tmux.conf && tmux source-file ~/.tmux.conf"
alias aptup="sudo apt update && sudo apt upgrade && sudo apt autoremove"
alias up="sudo apt update && sudo apt upgrade && sudo apt autoremove && composer global update && npm update -g && sudo gem update --system && sudo snap refresh"
alias top="gotop -psbc monokai"
alias iftop="sudo iftop"
alias powertop="sudo powertop"
alias fuck='sudo "$BASH" -c "$(history p !!)"'
alias work="cd ~/Work/src/github.com/"
alias gml="git checkout master && git pull && git remote prune origin"
alias privatefox="firefox -private"
alias inchrome="google-chrome --incognito"
alias macos="cd ~/Downloads/macOS && sh basic.sh"
alias listwifis='nmcli -f in-use,ssid,bssid,signal,bars dev wifi'
alias latestdocker='docker exec -it `docker ps -q --latest` /bin/sh'

export GOPATH=$HOME/Work
export GO111MODULE=on
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export ANDROID_HOME=$HOME/Android/Sdk
export REACT_EDITOR=vim
export EDITOR=vim
export EVENT_NOKQUEUE=1
export GPG_TTY=$(tty)
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export NVM_DIR="/home/gcg/.nvm"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH=$PATH:/snap/bin
export PATH=$PATH:$GOPATH/bin

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH="/usr/local/sbin:$PATH"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$HOME/Apps/Postman:$PATH"
export PATH="$HOME/Apps/android-studio:$PATH"
export PATH="$PATH:$HOME/.npm/bin"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH=~/.composer/vendor/bin:$PATH
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$HOME/.tmux/bin
